### PR TITLE
Civil Surface added

### PR DESCRIPTION
**Pull request by atultegar**
Hi Paolo,

I have forked the CivilConnection from GitHub and added some of the additional Dynamo nodes related to Civil 3D surfaces, as they are not included in the current version of CivilConnection.

I have tested the CivilConnection package with new nodes using Autodesk Civil 3D 2019 and Revit 2019, but the same nodes can work for 2020 version also.

I created nodes as they are useful for us in our current projects.
e.g. 
1. GetElevationAtPoint for getting selected surface elevation at a point to update the foundation depth of structure or pile. 
2. GetElevationsAlongLine is useful to generate a surface profile along a line in Revit
3. GetPointsInsidePolygon together with GetElevationsAlongLine is used to create a topography of a selected area.
The details of all new Dynamo nodes are in the attached file.
[CivilConnectionContribution.docx](https://github.com/Autodesk/civilconnection/files/3590063/CivilConnectionContribution.docx)

### CODE REVIEW

**Comment by paoloemilioserra** [comment]
@atultegar thanks for this, I'm happy you are contributing back to the project and that this is working for you in your workflows. The code you provided at the moment is not ready for merging but I see how it can be useful to others.
Could you please complete the descriptions in the code in the "\<summary\>" tags?
Also you should please implement comparison tests that take into account roundings when you are checking for numerical values (e.g. I usually use a rounding to the 5th decimal digit).
Please, rename the variable names in the functions so that they would start with a lowercase letter to avoid confusion with class names. 
In general, the moment we introduce CivilSurfaces, there will be need to display those surfaces in Dynamo. Could you implement these changes and missing features? we'll need to check also that there are no "dead" geometry objects in the code. and correctly dispose them. Currently I don't have the bandwidth to do this myself, so any help in these regards is very much appreciated.

**Comment by danielgijsbers** [comment]
@atultegar great work, some of your colleauges are needing nodes for surfaces as well. I would be greatly appreciated if you could grant @paoloemilioserra requests. :)

**Comment by atultegar** [comment]
Hi @paoloemilioserra , I have implemented all the summary tags and numerical values rounding to  digits, checked all the variable names as mentioned in your comment.
Also, for surface we can show surface in Dynamo by creating surfaces for each triangle from Civil 3D surface.
And I'm still working on finding out the solution to create a cropped surface inside Dynamo, but we can create cropped surface topography in Revit by using points inside polygon and points along polygon lines.
Thanks :)

**Comment by paoloemilioserra** [comment]
@atultegar, please complete also the param tags, sorry I was too specific in my previous comment.
Also the return type can you replace the "object" for what it actually is? 
Also there is no consistent logging info for the functions when they are starting and when they are ending, etc... this is for consistency with the rest of the code.
Could you please implement the geometry representation as well, I want to understand if this is manageable (not feasible) in Dynamo when you have in the order of millions of triangles.

There are already CivilPoint and CivilPointGroup in CivilConnection, could you look into a constructor method for the CivilSurface (when I looked into it I got a roadblock in COM, might need to take a look at reflection).
Thanks.

**Comment by atultegar** [comment]
Hi Paolo,
I tried to update the method AddTinSurfaceByPoints by creating a new class tinData in Utils.cs as 
```
private class tinData : AeccTinCreationData
        {
            public string Name { get ; set; }
            public string Description { get; set; }
            public string Style { get; set ; }
            public string Layer { get ; set; }
            public string BaseLayer { get ; set; }
        }
```
and then create an object from this class, and it works well.
So, where should I place this class, inside Utils.cs or CivilSurface.cs?
Also, should I include this surface constructor method in CivilSurface.cs?

Thanks

**Comment by paoloemilioserra** [comment]
@atultegar I tried but I'm still getting the same error on the COM API even with reflection.
EDIT
I was able to make it work with your suggestion of the derived class but the Civil 3D file is really unstable afterward, it requires some investigation.

**Comment by atultegar** [comment]
`
//this is  what I have implemented

        private class tinData : AeccTinCreationData
        {
            public string Name { get ; set; }
            public string Description { get; set; }
            public string Style { get; set ; }
            public string Layer { get ; set; }
            public string BaseLayer { get ; set; }
        }

        /// <summary>
        /// Adds a TIN surface by points.
        /// </summary>
        /// <param name="doc">The document.</param>
        /// <param name="points">The points.</param>
        /// <param name="name">The name.</param>
        /// <param name="layer">The name of the layer.</param>
        /// <returns></returns>
        [IsVisibleInDynamoLibrary(false)]
        public static string AddTINSurfaceByPoints(AeccRoadwayDocument doc, Point[] points, string name, string layer)
        {
            Utils.Log(string.Format("Utils.AddTINSurfaceByPoints started...", ""));

            string handle = "eNull";

            try
            {
                AddLayer(doc, layer);

                AeccPointGroup group = doc.HandleToObject(AddPointGroupByPoint(doc, points, name)) as AeccPointGroup;

                AeccSurfaces surfaces = doc.Surfaces;

                Type surfacesType = surfaces.GetType();

                if (surfacesType != null)
                {
                    //AeccTinCreationData data = new AeccTinCreationData()
                    //{
                    //    BaseLayer = layer,
                    //    Description = "Created by Autodesk CivilConnection",
                    //    Layer = layer,
                    //    Name = name,
                    //    Style = doc.SurfaceStyles.Cast<AeccSurfaceStyle>().First().Name
                    //};
                    //};

                    //dynamic surf = surfacesType.InvokeMember("AddTinSurface",
                    //    BindingFlags.InvokeMethod,
                    //    System.Type.DefaultBinder,
                    //    surfaces,
                    //    new object[] { new AeccTinCreationData() });

                    //handle = "eDebug - AeccTinCreationData";

                    // AeccTinSurface surface = surfaces.AddTinSurface(data);

                    // surf.PointGroups.Add(group);

                    //handle = surf.Handle;

                    tinData data = new tinData
                    {
                        BaseLayer = layer,
                        Description = "Created by Autodesk CivilConnection",
                        Layer = layer,
                        Name = name,
                        Style = doc.SurfaceStyles.Cast<AeccSurfaceStyle>().First().Name
                    };

                    AeccTinSurface surf = surfaces.AddTinSurface(data);

                    surf.PointGroups.Add(group);

                    handle = surf.Handle;

                }
            }
            catch (Exception ex)
            {
                Utils.Log(string.Format("ERROR: Utils.AddTINSurfaceByPoints {0}", ex.Message));

                throw ex;
            }

            Utils.Log(string.Format("Utils.AddTINSurfaceByPoints completed.", ""));

            return handle;
        }`

**Comment by paoloemilioserra** [comment]
yes, it's the same thing on my end but the Civil 3D file doesn't respond well anymore after the surface was created.

**Comment by paoloemilioserra** [comment]
Added in [2.0.0](https://github.com/Autodesk/civilconnection/commit/5cdc8042a15eee44eee3c91241eb953a065e5ce0)

**Pull request closed without merging**
